name: Build CLI


on:
	push:
		branches: [ main ]
	pull_request:
		branches: [ main ]


jobs:
	build_and_test:
		runs-on: ubuntu-latest


		steps:
			- uses:	actions/checkout@v3

			- name: Check Golang CLI
				uses: actions/setup-go@v3
				with:
					go-version: 1.19

			- name: Build
				run: cd cli
				run: go build