# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  lib_home: /usr/lib/x86_64-linux-gnu
  java_home: /usr/lib/jvm/java-1.17.0-openjdk-amd64/include

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build golib
      run: cd cli && go build -o libpackageanalyze.so -buildmode=c-shared main.go ; cd .. ; sudo cp cli/libpackageanalyze.* $lib_home

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build jheader
      run: cd cli && javac NetScoreMetric.java NetScoreUtil.java -h . ; cd ..
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Build clib
      run: cd cli && sudo g++ -fPIC -I"$JAVA_HOME" -I"$JAVA_HOME/linux" -shared -o $lib_home/libNetScoreUtil.so cli_NetScoreUtil.cpp libpackageanalyze.so ; cd ..
    
    - name: Test javalib
      run: java cli.NetScoreUtil
