name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  PROJECT_ID: springex-64fb3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Decode service account key
      run: echo ${{ secrets.PRIVATE_KEY }} | base64 --decode > accountKey.json

    - name: Set environment variables
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/accountKey.json
        export GOOGLE_CLOUD_PROJECT=$PROJECT_ID

    - name: Replace sensitive information in application.properties
      run: |
        sed "s/\${KEYSTORE_PASSWORD}/${KEYSTORE_PASSWORD}/g" api_paths/src/main/resources/application.properties > api_paths/src/main/resources/application.properties

    - name: Build with Maven
      run: mvn package
      working-directory: api_paths

    - name: Build for Docker
      run: |
        docker build -t my-docker-image .
        docker run --rm -d -p 8080:8080 --name my-docker-container -v ${PWD}/api_paths/src/main/resources/application.properties:/app/resources/application.properties my-docker-image
        sleep 30

    - name: Verify Spring Boot application
      run: |
        curl http://localhost:8080/
      
    - name: Stop Docker container
      run: docker stop my-docker-container
